# Working with Jupyter Notebooks and Numpy 

## Jupyter Notebooks

In [127]:
print("Well this is fun")
# Use ctrl/cmd+ Enter to run the cell and move to the next

Well this is fun


In [128]:
lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [129]:
!dir

 Volume in drive C is SSD
 Volume Serial Number is 1EF7-B29B

 Directory of C:\Users\Dan\Dev\data-science-with-anaconda\ch_4

04/11/22  08:46 PM    <DIR>          .
04/11/22  08:46 PM    <DIR>          ..
04/11/22  08:08 PM    <DIR>          .ipynb_checkpoints
04/11/22  08:46 PM            32,538 numpy_101.ipynb
10/03/21  10:12 PM             1,193 temp_data_c.txt
10/03/21  10:11 PM             1,188 temp_data_f.txt
09/10/21  06:02 AM                18 test.py
04/11/22  08:18 PM            10,503 Working with Jupyter Notebooks.ipynb
               5 File(s)         45,440 bytes
               3 Dir(s)  26,239,852,544 bytes free


## Creating and Manipulating Numpy arrays

In [1]:
import numpy as np
import random
import math
import array

In [131]:
np.array([1,2,3])

array([1, 2, 3])

In [132]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [133]:
arr * 3

array([3, 6, 9])

In [134]:
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d.shape

(2, 3)

In [135]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
print(arr_2d.shape)
print(arr.shape)

(2, 3)
(3,)


In [137]:
arr = np.array([1,2,3]) 

In [138]:
arr.shape

(3,)

In [139]:
#### They HAVE to have the same lenght, will get an error otherwise
a = np.array([[2,3,5],[65,45,34]])
print(a)

[[ 2  3  5]
 [65 45 34]]


In [140]:
a[1,1]

45

In [141]:
a[0,:]

array([2, 3, 5])

In [142]:
# All 0s matrix
np.zeros((3,4))
# All 1s matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [143]:
np.full((2,2), 88) 

array([[88, 88],
       [88, 88]])

In [144]:
#random from 0-1
np.random.rand(4,2)

array([[0.50242865, 0.0439286 ],
       [0.14664006, 0.25918728],
       [0.56522557, 0.81299657],
       [0.48822657, 0.1808333 ]])

In [145]:
#random from 0-1
np.random.randint(-10,99, size = (3,3))

array([[75,  9, 36],
       [11, 73, 14],
       [-7, 29, 26]])

In [2]:
np.random.randint(0,100, (2,3))

array([[40, 39, 23],
       [10, 87, 93]])

In [146]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [147]:
np.ones((5,5))

(shape, dtype, order)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [148]:
np.max


<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

arr = np.array([1,2,3]) 

In [149]:
print(arr)

[1 2 3]


#### Basic mathematical operations 

In [150]:
arr = np.array([1,2,3])

In [151]:
arr + 3

array([4, 5, 6])

In [152]:
arr - 1

array([0, 1, 2])

In [153]:
arr * 3

array([3, 6, 9])

In [154]:
arr / 2  

array([0.5, 1. , 1.5])

In [155]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### Analyzing Mars Sensor data with Numpy

In [156]:
arr_1 = np.genfromtxt('mars_temp_data_f.txt', delimiter=',')

In [157]:
arr_1 > 20

array([[ True, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [ True,  True, False, False,  True, False,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, 

In [158]:
arr_1[arr_1 > 20]

array([25., 38., 31., 34., 37., 21., 35., 23., 22., 23., 21., 21., 36.,
       34., 30., 28., 28., 21., 34., 38., 31., 25., 23., 23., 31., 29.,
       27., 30., 33., 36., 25., 37., 23., 31., 38., 31.])

In [159]:
arr_conv_cel = (arr_1 - 32) * .5556
arr_conv_cel[arr_conv_cel>10]

array([], dtype=float64)

## Comparing speed of arrays vs numpy arrays

In [160]:
simple_list = [1,2,3]
np_arr = np.array([1,2,3])

In [161]:
%timeit random.choices(simple_list, k=10)

2.56 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [162]:
%timeit np.random.choice(np_arr, size=10)

19.1 µs ± 82.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [163]:
%timeit random.choices(simple_list, k=100)

15.9 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [164]:
%timeit np.random.choice(np_arr, size=100)

20.1 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### Large arrays/lists

In [165]:
%timeit random.choices(simple_list, k=1000000)

158 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [166]:
%timeit np.random.choice(np_arr, size=1000000)

12.9 ms ± 99.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [167]:
#If you want something smaller, you can specefy the data type to use , dtype = 'int16'
a = np.array([1,2,3])
print(a)

[1 2 3]


In [168]:
b = np.array([[9,3,2.3], [5,3,3.4]])
print(b)

[[9.  3.  2.3]
 [5.  3.  3.4]]


In [169]:
b.ndim

2

In [170]:
#Get Shape
a.shape

(3,)

In [171]:
b.shape

(2, 3)

In [172]:
foo = np.array([[1,2],[3,4],[5,6],[7,8]])
foo.shape

(4, 2)

In [173]:
# Get type
a.dtype

dtype('int32')

In [174]:
# Get how many bytes are designated
a.itemsize

4

In [175]:
# Get the number of bytes
a.nbytes

12

In [176]:
# Floats are a lot bigger than normal ints
b.nbytes

48