# Working with Jupyter Notebooks and Numpy 

## Jupyter Notebooks

In [1]:
print("Well this is fun")
# Use ctrl/cmd+ Enter to run the cell and move to the next

Well this is fun


In [2]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [ ]:
# You can also run commands that describe your local directory.

!dir

## Creating and Manipulating Numpy arrays

In [4]:
import numpy as np
import random
import math
import array

In [5]:
arr = np.array([1,2,3])

In [6]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
arr * 3

array([3, 6, 9])

In [8]:
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d.shape

(2, 3)

In [9]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
print(arr_2d.shape)
print(arr.shape)

(2, 3)
(3,)


In [11]:
arr = np.array([1,2,3]) 

In [12]:
arr.shape

(3,)

In [13]:
#### They HAVE to have the same lenght, will get an error otherwise
a = np.array([[2,3,5],[65,45,34]])
print(a)

[[ 2  3  5]
 [65 45 34]]


In [14]:
a[1,1]

45

In [15]:
a[0,:]

array([2, 3, 5])

In [16]:
# All 0s matrix
np.zeros((3,4))
# All 1s matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((2,2), 88) 

array([[88, 88],
       [88, 88]])

In [18]:
#random from 0-1
np.random.rand(4,2)

array([[0.18094353, 0.46299638],
       [0.14674221, 0.15390857],
       [0.18930471, 0.47763655],
       [0.62728102, 0.09781056]])

In [19]:
#random from 0-1
np.random.randint(-10,99, size = (3,3))

array([[32, 34, 52],
       [52, 95, 39],
       [86, 34, -1]])

In [20]:
np.random.randint(0,100, (2,3))

array([[90, 10, 44],
       [50, 87, 30]])

In [21]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
ones = np.ones((5,5))

In [23]:
np.max(ones)

1.0

arr = np.array([1,2,3]) 

In [24]:
print(arr)

[1 2 3]


#### Basic mathematical operations 

In [25]:
arr = np.array([1,2,3])

In [26]:
arr + 3

array([4, 5, 6])

In [27]:
arr - 1

array([0, 1, 2])

In [28]:
arr * 3

array([3, 6, 9])

In [29]:
arr / 2  

array([0.5, 1. , 1.5])

In [30]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### Analyzing Mars Sensor data with Numpy

In [31]:
arr_1 = np.genfromtxt('temp_data_f.txt', delimiter=',')

In [32]:
arr_1 > 20

array([[ True, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [ True,  True, False, False,  True, False,  True,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, 

In [33]:
arr_1[arr_1 > 20]

array([25., 38., 31., 34., 37., 21., 35., 23., 22., 23., 21., 21., 36.,
       34., 30., 28., 28., 21., 34., 38., 31., 25., 23., 23., 31., 29.,
       27., 30., 33., 36., 25., 37., 23., 31., 38., 31.])

In [34]:
arr_conv_cel = (arr_1 - 32) * .5556
arr_conv_cel[arr_conv_cel>10]

array([], dtype=float64)

## Comparing speed of arrays vs numpy arrays

In [35]:
simple_list = [1,2,3]
np_arr = np.array([1,2,3])

In [36]:
%timeit random.choices(simple_list, k=10)

1.61 µs ± 57.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [37]:
%timeit np.random.choice(np_arr, size=10)

12.3 µs ± 727 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [38]:
%timeit random.choices(simple_list, k=100)

9.4 µs ± 342 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [39]:
%timeit np.random.choice(np_arr, size=100)

13.2 µs ± 387 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### Large arrays/lists

In [40]:
%timeit random.choices(simple_list, k=1000000)

95.6 ms ± 2.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit np.random.choice(np_arr, size=1000000)

10.5 ms ± 96.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [42]:
#If you want something smaller, you can specefy the data type to use , dtype = 'int16'
a = np.array([1,2,3])
print(a)

[1 2 3]


In [43]:
b = np.array([[9,3,2.3], [5,3,3.4]])
print(b)

[[9.  3.  2.3]
 [5.  3.  3.4]]


In [44]:
b.ndim

2

In [45]:
#Get Shape
a.shape

(3,)

In [46]:
b.shape

(2, 3)

In [47]:
foo = np.array([[1,2],[3,4],[5,6],[7,8]])
foo.shape

(4, 2)

In [48]:
# Get type
a.dtype

dtype('int32')

In [49]:
# Get how many bytes are designated
a.itemsize

4

In [50]:
# Get the number of bytes
a.nbytes

12

In [51]:
# Floats are a lot bigger than normal ints
b.nbytes

48